version: '3'
services:
  demo-app:
    build:
      .
    volumes:
      - .dockervenv:/src/.venv
      - .:/src
    ports:
      - "8000:8000" # 호스트머신의 8000번 포트와 컨테이너의 8000번 포트를 연결
    environment:
      - WATCHFILES_FORCE_POLLING=true # 환경에 따라 핫 리로딩을 위해 감시 파일을 강제로 폴링하도록 설정 # 자동으로 코드가 변경되면 서버가 다시 시작됨

  db:
    image: mysql:8.0
    platform: linux/x86_64 # 애플 실리콘 등 ARM기반일 경우 필요
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: "demo"
      TZ: "Asia/Seoul"
    volumes:
      - mysql-data:/var/lib/mysql
    command: 
      --default-authentication-plugin=mysql_native_password
      # MYSQL에서는 8.0부터 caching_sha2_password가 기본 인증 플러그인이 되었음
      # 이를 해결하기 위해 mysql_native_password를 사용하도록 설정
    ports:
      - "33306:3306" # 호스트머신의 33306번 포트와 컨테이너의 3306번 포트를 연결
volumes:
  mysql-data: