# 파이썬 3.11 이미지 다운
FROM  python:3.11-buster

# 파이썬의 출력 표시를 Docker용으로 조정
ENV PYTHONUNBUFFERED=1

WORKDIR /src

RUN pip install "poetry==1.6.1"

COPY pyproject.toml* poetry.lock* ./

COPY api api
COPY entrypoint.sh ./

RUN poetry config virtualenvs.in-project true
RUN if [ -f pyproject.toml ]; then poetry install --no-root; fi

ENTRYPOINT ["bash", "entrypoint.sh"]